"""add last_edit from sketch

Revision ID: 236e85c30c9c
Revises: 251eebe58d64
Create Date: 2015-08-25 10:59:11.042505

"""

# revision identifiers, used by Alembic.
revision = '236e85c30c9c'
down_revision = '251eebe58d64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sketches', sa.Column('last_edit', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sketches', 'last_edit')
    ### end Alembic commands ###
