"""initial migration

Revision ID: 251eebe58d64
Revises: None
Create Date: 2015-08-24 22:34:52.399568

"""

# revision identifiers, used by Alembic.
revision = '251eebe58d64'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sketches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Sketches_title'), 'Sketches', ['title'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Sketches_title'), table_name='Sketches')
    op.drop_table('Sketches')
    ### end Alembic commands ###
