"""add password support

Revision ID: 2ebde1faa16f
Revises: 475567e542b1
Create Date: 2015-08-17 13:43:35.833590

"""

# revision identifiers, used by Alembic.
revision = '2ebde1faa16f'
down_revision = '475567e542b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
